### ISSUE TITLE
total_count is erroneously None

### ISSUE THREAD

**Issue by racheesingh** [RIPE-NCC/ripe-atlas-cousteau#18]
The object returned by ProbeRequest does not have total_count set even when a non-zero number of probes have matched the filter. Here is the version information:

Name: ripe.atlas.cousteau
Version: 0.9.2
Summary: Python wrapper for RIPE Atlas API
Home-page: https://github.com/RIPE-NCC/ripe-atlas-cousteau
...
Location: /Library/Python/2.7/site-packages

**Comment by astrikos** [comment]
Could you try with a later version? maybe latest and see if you can reproduce it?
