### ISSUE TITLE
Error installing in ArchLinux

### ISSUE THREAD

**Issue by francrodriguez** [RIPE-NCC/ripe-atlas-cousteau#21]
In an Archlinux up to date, i get this error when I try to install ripe-atlas-tools.
To reproduce it I just try to install ripe-atlas-tools form AUR with yaourt.

Copying ripe.atlas.cousteau.egg-info to /var/tmp/yaourt-tmp-franc/aur-python-ripe-atlas-cousteau/pkg/python-ripe-atlas-cousteau/usr/lib/python3.5/site-packages/ripe.atlas.cousteau-1.0.6-py3.5.egg-info
Installing /var/tmp/yaourt-tmp-franc/aur-python-ripe-atlas-cousteau/pkg/python-ripe-atlas-cousteau/usr/lib/python3.5/site-packages/ripe.atlas.cousteau-1.0.6-py3.5-nspkg.pth
running install_scripts
rm: cannot remove 'ripe/__pycache__': No such file or directory
rm: cannot remove 'ripe/atlas/__pycache__': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build .

**Comment by danielquinn** [comment]
Thanks for your report!  @Woutifier contributed that code, so I'm flagging him here so that we can talk about it some.  Wouter, do you have any ideas on this one?  If not, I'll see about spinning up an Arch vagrant box and debugging this myself.

**Comment by Woutifier** [comment]
Let me see what is going on :)

**Comment by Woutifier** [comment]
I've updated the package. It should install without errors now. Thanks for letting us know!

**Comment by francrodriguez** [comment]
Great Job! ripe-atlas-tools installed :+1: 
Thank you!
