### ISSUE TITLE
Change measurement doesn't consider tags

### ISSUE THREAD

**Issue by pierky** [RIPE-NCC/ripe-atlas-cousteau#25]
Hello,

I used the code [1] provided [here](https://ripe-atlas-cousteau.readthedocs.org/en/latest/use.html#changing-measurement-sources) to add some probes to msm ID 3513990: I wanted the _system-ipv4-works_ to be added to the source, but even if the change request was fine I can't find the tag in the web UI.

I did it for 3 different ASNs, I tried also a direct call to the v2 API [2] but I had no success.

As you can see from the msm only the first set of probes that I added via the web UI has the tag.

Could you point me in the right direction to have change requests considering tags?

Thanks

1) the code I used:

```
from ripe.atlas.cousteau import AtlasChangeSource, AtlasChangeRequest

ATLAS_MODIFY_API_KEY = "MY_CHANGE_KEY"

# Add probes
source = AtlasChangeSource(
        value="1234567890",
        requested=5,
        type="asn",
        tags={
                "include": ["system-ipv4-works"],
                "exclude": ["system-anchor"]
        },
        action="add"
)

atlas_request = AtlasChangeRequest(
        key=ATLAS_MODIFY_API_KEY,
        msm_id=3513990,
        sources=[source]
)

(is_success, response) = atlas_request.create()

print(is_success)
print(response)
```

2) API call:

```
curl --dump-header - -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{
 "action": "add",
 "requested": 5,
 "type": "asn",
 "value": "1234567890",
 "tags": {
   "include": [
     "system-ipv4-works"
   ],
   "exclude": []
 }
}' https://atlas.ripe.net/api/v2/measurements/3513990/participation-requests/?key=XXXXXXXX
```

**Comment by astrikos** [comment]
Hi Pier, it should be in somewhere in[AtlasChangeSource](https://github.com/RIPE-NCC/ripe-atlas-cousteau/blob/master/ripe/atlas/cousteau/source.py#L152-L233) class. I will have a look soon unless you want to dive in yourself.

**Comment by pierky** [comment]
Hi, I had problems with a manual API call too, so I thought it was a problem in the backend.

From the same code, if I execute

```
atlas_request._construct_post_data()
print(atlas_request.post_data)
```

I get

```
[{'action': 'add', 'requested': 5, 'type': 'asn', 'value': '1234567890', 'tags': {'exclude': ['system-anchor'], 'include': ['system-ipv4-works']}}]
```

so it seems the POST data is the same I used in my manual API call.

**Comment by astrikos** [comment]
hm okay I thought that was working after #5, but maybe something got broke in our backend in the meantime. I will check.

**Comment by astrikos** [comment]
That should now be fixed, it was indeed a backend issue, which we pushed a fix today.

**Comment by pierky** [comment]
Thanks, I can confirm that now it's working fine.
