### ISSUE TITLE
Problems with timestamps.

### ISSUE THREAD

**Issue by crauterb** [RIPE-NCC/ripe-atlas-cousteau#26]
Hey guys,

first off: great library guys, really makes working with the atlas nodes easy :-)
Right now I am having some trouble seeting up measurments on nodes, as it keeps exploding in my face due to some problem with the time stamps.
Right now I just want to make sure I didn't make some stupid mistake....

So, I was following your basic examples in your documention and therefore stated the start time by using: 
```python
datetime.datetime.utcnow()
```
Which then gives my this as on output:
```
Current time UTC is: 2016-02-17 05:42:14.802293  ==  1455655334
Current time is: 2016-02-17 14:42:14.802372  ==  1455687734
Measurement starts at: 2016-02-17 05:44:14.802278  ==  1455655454
--->Shit went wrong
Atlas start: 1455655454
T_Time: 1455655454
{'status': 400, 'detail': 'start_time: Ensure this value is greater than or equal to 1455687970.', 'title': None, 'code': 104}
```
from a starting a simple DNS query following the example "Creating a measurment" in your docs.

I am currently working in Japan, therefore UTC and my timestamp differ. 
So far, no harm done - I can just use my currenty time stamp - meaning
```python
datetime.datetime.now()
```
I can submit those request, but then my measurments will not start right away but in 8 hours (=time difference between UTC and Tokyo time).
As far as I see, somewhere along the way, something gets mixed up with the time stamps!

No I am not sure if I missinterpreted the documention of your tools somehow and made a mistake along the way or if this is acutally an issue. 

e.g. in ripe-atlas-cousteau/ripe/atlas/cousteau/api_listing.py, l.63ff.,  you reduce several objects to simpler objects, i.e.:
```python
for k, v in self.api_filters.items():
            if isinstance(v, datetime):  # datetime > UNIX timestamp
                self.api_filters[k] = int(calendar.timegm(v.timetuple()))
            if isinstance(v, (tuple, list)):  # tuples & lists > x,y,z
                self.api_filters[k] = ",".join([str(_) for _ in v])
```
Yet, on my computer, I get this:
```python
>>> import datetime
>>> import calendar
>>> datetime.datetime.utcnow()
datetime.datetime(2016, 2, 17, 5, 33, 34, 832888)
>>> datetime.datetime.utcnow().timetuple()
time.struct_time(tm_year=2016, tm_mon=2, tm_mday=17, tm_hour=5, tm_min=34, tm_sec=16, tm_wday=2, tm_yday=48, tm_isdst=-1)
>>> datetime.datetime.utcnow().strftime("%s")
'1455654879'
>>> calendar.timegm(datetime.datetime.utcnow().timetuple())
1455687298
```
This explains at least why I get an error when using the normal UTC time...

Anyways, sorry for the long text, hope it is all understandable.
I'd love your oppinion on this :)

Cheers,
Chris

**Comment by astrikos** [comment]
Hi Chris,

where do you create the start time? is it long time before you call the create? If you call it some time before you do the query then the post data specs that will reach the backend servers will have a start time that it's already in the past. So you will get denied.
If you execute the exact code as in docs and you run all lines immediately it should work (I just tested it). If you want to debug more can you print the post data? After you create the request just do:

`
print atlas_request.post_data
`

Also if you want to make you measurement start now you can omit start time and RIPE Atlas backend will start it immediately.

The difference in _calendar.timegm_ and _strftime_ is that calendar will convert from UTC timestamp , ,strftime on the other hand converts from local time not UTC. That is why you see these differences.

Let me know if you need more help.

**Comment by crauterb** [comment]
Hey man,
thankx for the quick reply. As it turns out, it was just a stupid mistake on my part. 
Due to some typo in calculating the time difference between my errors I now realize, that there was a problem with my hardware clock on my Linux. Enabling time sync over network solved the whole thing.

Stupid, but anyway, now its solved and I run measurement with any offeset I want.
Thanks for the help!
