### ISSUE TITLE
Unable to use library with proxies

### ISSUE THREAD

**Issue by kemals** [RIPE-NCC/ripe-atlas-cousteau#28]
There are two issues with proxies:

1. `AtlasCreateRequest` is using requests and based on current implementation of request.py there was no easy way of using proxy.

2. We wanted to fetch results using the stream api and based on current implementation of stream.py and the fact that it is using SocketIO we can't use proxy. 

We managed to work around the first issue by setting an env variable for the proxy and that worked, so creating request works. However, fetching results with stream api and SocketIO proved to be problem with proxy. 

It looks like you can use proxies with SocketIO but this would need adding: https://pypi.python.org/pypi/socketIO-client

**Comment by astrikos** [comment]
> It looks like you can use proxies with SocketIO but this would need adding: https://pypi.python.org/pypi/socketIO-client

We already use this lib for the stream API, so it should possible. I am wandering why it didn't pick up the env variable automatically, since they also use requests.
