### ISSUE TITLE
Cousteau should raise an exception when invalid filters are used

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-cousteau#29]
I needed a list of probes in Canada, so I did this:

``` python
list(ProbeRequest(country="ca"))
```

Then I waited a Very Long Time until I just killed the process.

After some poking at the source code, I realised that `country=` was an invalid filter, so then I went looking for the right value in the documentation.  [The answer was not immediately obvious](https://atlas.ripe.net/docs/api/v2/manual/probes/) and Jasper pointed me to the [reference manual](https://atlas.ripe.net/docs/api/v2/reference/#!/probes) which I didn't find while looking.

I finally realised that I needed `country_code=`, which is fine, but it'd be nicer if Cousteau was smart enough to either (a) tell me that `country=` was invalid (rather than just grabbing all of the probes) or (b) pointed out my mistake and did some fuzzy matching to guess what I wanted (or at least present all options).

**Comment by astrikos** [comment]
hey Dan,
not sure I want to take the road of validating input from users. It will increase complexity significantly and it will need additional changes as soon as we change API. I would rather keep cousteau dump and implement this kind of validation on API instead, where all the people would benefit from it.

**Comment by danielquinn** [comment]
Normally I would agree, but I wasn't the only one running into this at the hackathon and griping about it.  Perhaps something auto-configuring like what I did recently at my current gig [here](https://github.com/UKTradeInvestment/export-wins-ui/blob/master/alice/metaclasses.py)?  Basically you do one API call to get the API schema rules (filter fields, field types, restrictions etc.) and then use that to do client-side error handling?  You could even cache the schema request on a 1hour basis or something for performance if you like.
