### ISSUE TITLE
Stream hangs forever on socket.io error

### ISSUE THREAD

**Issue by romain-fontugne** [RIPE-NCC/ripe-atlas-cousteau#30]
Hi there,

While fetching stream results with cousteau, I got the following error message in my terminal: 
`WARNING:root:atlas-stream.ripe.net:80//stream/socket.io [connection error] unexpected status code (400 {"code":1, "message":"Session ID unknown"})`

And cousteau hangs forever (notice that I haven't set a timeout) so there is no way to recover from this error. I have googled the error and it seems that this could be solved on the server side (e.g.  https://github.com/socketio/socket.io/issues/1739 and https://github.com/socketio/socket.io-client-swift/issues/237)

**Comment by MaxCam** [comment]
Hi Romain,
Could you check if the issue still present? It can be that was a temporary problem we had with the servers.
Both atlas-cli and Couseau work for me.

**Comment by romain-fontugne** [comment]
Hi Massimo,
Thank you, I have started a new run. I'll let you know if it is fixed.

**Comment by romain-fontugne** [comment]
Thanks Massimo, it seems to be fixed!
