### ISSUE TITLE
Latest release is tagged 1.4.2 rather than v1.4.2

### ISSUE THREAD

**Issue by RaitoBezarius** [RIPE-NCC/ripe-atlas-cousteau#59]
Hi there, thank you for the project, I just noticed (during packaging this library for NixOS) that latest release is tagged 1.4.2 instead of v1.4.2, which is different from the usual naming convention from what I gather.

That would be awesome if it could be tagged v1.4.2 too!

**Comment by chrisamin** [comment]
Hey there! Good catch, yes I have now tagged master as "v1.4.2", which is the same as "1.4.2" except for adding the missing changelog and some metadata changes. However, I am also planning on releasing a new version in the next couple of weeks, in case you want to hold off on your packaging efforts.

**Comment by RaitoBezarius** [comment]
Hi again! Awesome, thank you. Well, the packaging code has been pretty much written here: https://github.com/NixOS/nixpkgs/pull/155270 and it will be more or less trivial to bump the version to the latest one once you release, so no worries, and thank you a lot for your work. :)
