### ISSUE TITLE
websocket-client dependency?

### ISSUE THREAD

**Issue by RaitoBezarius** [RIPE-NCC/ripe-atlas-cousteau#60]
Reading the `setup.py`, I see that there is a dependency on `websocket-client<0.99`, I have two questions regarding that:

(1) is `websocket-client` directly used as a dependency of this project? It appears to me this is the responsibility of `socketio-client`, am I right assuming that?
(2) moving forward with this assumption, it looks like there was a will to pin the transitive dependency to avoid a bug or something, is it right? Do you know if the desired behavior is now in the latest version of the library, can the pin be removed or documented instead?

(for context, this is still about packaging it in NixOS, I had to patch out the `<0.99` constraint as `socketio-client` have a quite recent version of that!)
Many thanks!

**Comment by chrisamin** [comment]
Yes, this was probably to avoid a bug. I will check for the next release that I am currently working on (probably either 1.4.3 or 1.5.0 depending on how much ends up getting changed).

**Comment by RaitoBezarius** [comment]
Awesome, if you feel this can be closed, feel free to do it!

**Comment by chrisamin** [comment]
Fixed in v1.5.0
