### ISSUE TITLE
Support for python-socketio[client] >= 5?

### ISSUE THREAD

**Issue by robert-scheck** [RIPE-NCC/ripe-atlas-cousteau#63]
As of writing, ripe-atlas-cousteau depends on `python-socketio[client]<5`, while version 5 was released in December 2020 (see: https://pypi.org/project/python-socketio/). Do you see any chance for effectively supporting `python-socketio[client]>=4,<6`?

**Comment by chrisamin** [comment]
Closing this because socketIO has been dropped. We're using websocket-client~=1.3.1 at the moment because of a soft internal dependency on Python 3.6, but that restriction will be dropped soon.
